books/urls.py
from django.urls import path
from books import views
from books import apis

app_name = "books"

urlpatterns = [
    #API urls
    path('api/get_books/', apis.BooksViewSet.as_view({'get':'get_books'})),
    path('api/register_books/', apis.BooksViewSet.as_view({'post':'register_books'})),
    path('api/get_user_books/<int:book_id>/', apis.BooksViewSet.as_view({'get':'get_user_books'})),
    path('api/get_bookObject/<int:book_id>/', apis.BooksViewSet.as_view({'get':'get_bookObject'})),
    path('api/get_bookDetails/<int:book_id>/', apis.BooksViewSet.as_view({'get':'get_bookDetails'})),
    path('api/modify_book/<int:book_id>/', apis.BooksViewSet.as_view({'post':'modify_book'})),
    path('api/delete_book/<int:book_id>/', apis.BooksViewSet.as_view({'delete':'delete_book'})),
    path('api/get_comment_Object/<int:book_id>/', apis.CommentsViewSet.as_view({'get':'get_comment_Object'})),
    path('api/get_book_comments/<int:book_id>/', apis.CommentsViewSet.as_view({'get':'get_book_comments'})),
    # path('api/add_comment/', apis.CommentsViewSet.as_view({'post':'add_comment'})),
    path('api/add_comment/<int:book_id>/', apis.CommentsViewSet.as_view({'post':'add_comment'})),

    #Views urls
    path('home/', views.HomeView.as_view(), name="home"),
    path('registerBook/', views.RegisterBooksView.as_view(), name="registerBook"),
    path('bookDetails/<int:book_id>/', views.BookDetailsView.as_view(), name="bookDetails"),
    path('modify-book/<int:book_id>/', views.ModifyBookView.as_view(), name="modify-book"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
    path("books/", include("books.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # path("api/users/", include("users.urls")),
    # path("api/books/", include("books.urls")),

users/urls.py
from django.urls import path
from users import views
from users import apis

# from rest_framework.authtoken.views import obtain_auth_token

app_name = "users"

urlpatterns = [
    #all user apis

    path('api/get_UserObject/<int:user_id>/', apis.LoggedUserViewSet.as_view({'get':'get_UserObject'})),
    path('api/get_userDetails/<int:user_id>/', apis.LoggedUserViewSet.as_view({'get':'get_userDetails'})),
    path('api/update_user/<int:user_id>/', apis.LoggedUserViewSet.as_view({'post':'update_profile'})),

    path('api/logout/', apis.UsersViewSet.as_view({'post':'user_logout'})),
    path("api/registerUser/", apis.UsersViewSet.as_view({'post':'RegisterUser'})),
    path("api/allUsers/", apis.UsersViewSet.as_view({'get':'get_userList'})),
    path('api/loginUser/', apis.UsersViewSet.as_view({'post':'user_login'})),
    path('api/change_pass/', apis.UsersViewSet.as_view({'post':'change_pass'})),

    #all user views
    path('register/', views.RegisterUserView.as_view(), name="register"),
    path('update-profile/<int:user_id>/', views.UpdateProfileView.as_view(), name="update-profile"),
    path('all-users/', views.AllUsersView.as_view(), name="all-users"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('change-password/', views.ChangePasswordView.as_view(), name="change-password"),
    path('profile/<int:user_id>/', views.ProfileView.as_view(), name="profile"),
    
    # path('bookDetails/<int:book_id>/', views.UserDetailsView.as_view(), name="UserDetailsView"),
]

books/models.py
from django.db import models
from users.models import CustomUser

BOOK_TYPE_CHOICES = [('PHYSICAL', 'Physical'),
                    ('PAPERBACK', 'Paperback'),
                    ('DIGITAL', 'Digital')]

BOOK_LOCATION_CHOICES = [('HOME', 'Home'),
                    ('OFFICE', 'Office'),
                    ('INTO THE MATRIX', 'Into the Matrix')]

class Books(models.Model):
    title = models.CharField(max_length=250)
    authorName = models.CharField(max_length=250)
    authorEmail = models.CharField(max_length=250)
    bookType = models.CharField(max_length = 12, choices = BOOK_TYPE_CHOICES, default='Physical')
    bookLocation = models.CharField(max_length = 30, choices = BOOK_LOCATION_CHOICES, default='Home')
    description = models.TextField(max_length=300, default="User hasn't placed a bio yet.")
    added = models.DateTimeField(auto_now_add=True, auto_now=False)
    user = models.ForeignKey(CustomUser, on_delete = models.CASCADE, blank=True, null = True)
    coverImage = models.ImageField(blank=True, null=True, default='defaultCover.png', upload_to='books_images')

    def __str__(self):
        return self.title
    
    def total_likes(self):
        return self.likes.count()

class Comment(models.Model):
    book = models.ForeignKey(Books, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    body = models.TextField()

    class Meta:
        ordering = ['date_added']

    

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .managers import CustomUserManager
from django.utils.translation import gettext_lazy as _

from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token

class CustomUser(AbstractUser):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(_('email address'), max_length=255, unique=True)
    avatar = models.ImageField(blank=True, null=True, default='defaultAvatar.png', upload_to='profile_images')
    username = None

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    objects = CustomUserManager()

    bio = models.TextField(max_length=400)


    def __str__(self):
        return self.email

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

# Create your models here.

books/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView

class HomeView(TemplateView):
    template_name = "books/home.html"

    def get(self, request):
        return render(request, self.template_name)

class RegisterBooksView(TemplateView):
    template_name = "books/register_books.html"

    def get(self, request):
        return render(request, self.template_name)


class BookDetailsView(TemplateView):
    template_name = "books/bookDetails.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

class ModifyBookView(TemplateView):
    template_name = "books/modify_book.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

# Create your views here.

users/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView 

class AllUsersView(TemplateView):
    #test to list all users
    template_name = "users/index.html"

    def get(self, request):
        return render(request, self.template_name)

class LoginView(TemplateView):
    #test to list all users
    template_name = "users/login.html"

    def get(self, request):
        return render(request, self.template_name)

class RegisterUserView(TemplateView):
    template_name = "users/register_user.html"

    def get(self, request):
        return render(request, self.template_name)

class ChangePasswordView(TemplateView):
    template_name = "users/change_password.html"

    def get(self, request):
        return render(request, self.template_name)

class ProfileView(TemplateView):
    template_name = "users/profile.html"

    # def get(self, request, *args, **kwargs):
    #     return render(request, self.template_name)

class UpdateProfileView(TemplateView):
    template_name = "users/update_profile.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

# Create your views here.

templates/base.html
{% load static %}
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% comment %} ajax import {% endcomment %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        {% comment %} Bootstrap import {% endcomment %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    

        {% comment %} NAVBAR {% endcomment %}
  {% comment %} Start of Navbar {% endcomment %}
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #54BAB9;">
    <div class="container-fluid">
      
      <a class="navbar-brand" href="#">
        <img src="{% static '/bookIcon.png/' %}" width="30" height="30">
        Library
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'books:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'users:all-users' %}">User List</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:profile' user.id %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#" id="logoutLlink">Logout</a>
          </li>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:change-password' %}">Change Password</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'books:registerBook' %}">Register a Book</a>
        </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
          {% endif %}
        </ul>
      </div>
        <span class="navbar-text">
          {{user.email}}
        </span>
    </div>
  </nav>


    </head>

    <body>
        {% block content %}
        {% endblock %}
        
        <script>

            var firstname = "{{user.first_name}}"
            var lastname = "{{user.last_name}}"
        </script>
        {% comment %} Bootstrap JS import {% endcomment %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
        {% block extra_script %}

        {% endblock %}
    </body>

</html>

templates/books/bookDetails.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Book Details</h1>

<br><br>
{% comment %} <div class='container' id="bookDetailDisplay" style="justify-content: center; align-items: center;">
</div> {% endcomment %}

<div class='container' id="bookDetailDisplay">

    <div>
        {% if user.is_authenticated %}
            <div id="checkin"> 

            </div>
            <div id="checkout"> 

            </div>
            <div id="download"> 

            </div>
        {% else %}
            <p>You must log in to borrow/return books.</p>
        {% endif %}
    </div>
</div>

<br>

<h3>Comments</h3>
<div class='container' id="commentsDisplay">

</div>

<div class='container'>
    <h5>Add Comment</h5>
    {% if user.is_authenticated %}
        <p>Commenting as <strong>{{user.first_name}} {{user.last_name}}</strong></p>
        <form id="CommentForm">
            <div class="mb-3">
                <label for="InputComment" class="form-label"></label>     
                <input class="form-control" id="body" type="text" name="body">
            </div>
            <input type="submit" name="submit" value="Add Comment">
        </form>
    {% else %}
        <p>You are not logged in. You must log in to comment and modify own posts.</p>
        <a href="{% url 'users:login' %}">Log In</a>
    {% endif %}
</div>

<br>
<button type="button" id="deleteButton">Delete Book</button>
<br>


{% endblock %}

{% block extra_script %}
<script type="text/javascript" src="{% static 'books/book_details.js' %}"></script>
{% endblock %}

templates/books/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% if user.is_authenticated %}
    <h2>Welcome {{user.first_name}} {{user.last_name}}</h2>
{% else %}
    <h2>Please login</h2>
{% endif %}
<h1>Book List</h1>
<div id="dataDisplay" class="row">

</div>

<script type="text/javascript" src="{% static 'books/books.js' %}"></script>
{% endblock %}

templates/books/modify_book.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Modify Book</h1>
<br><br>
<div class='container' id="bookDetailDisplay" style="justify-content: center; align-items: center;">
</div>
<div class='container' style="justify-content: center; align-items: center;">
    <div class="position-relative">
        <form id="updateBookForm" id="bookFormDisplay">
            <div class="mb-3">
                <label for="InputTitle" class="form-label">Title: </label>
                <input class="form-control" id="title" type="text" name="title">
            </div>
            <div class="mb-3">
                <label for="InputDescription" class="form-label">Description: </label>
                <input class="form-control" id="description" type="text" name="description">
            </div>
            <div class="mb-3">
                <label for="InputCoverImage" class="form-label">Cover Image: </label>
                <input class="form-control" id="coverImage" type="file" name="coverImage">
            </div>
            <div class="mb-3">
                <select class="form-select" aria-label="Default Select Example" id="bookType" name="bookType">
                    <option value="">Select Book Type</option>
                    <option value="PHYSICAL">Physical</option>
                    <option value="PAPERBACK">Paperback</option>
                    <option value="DIGITAL">Digital</option>
                </select>
            </div>
            <div class="mb-3">
                <select class="form-select" aria-label="Default Select Example" id="bookLocation" name="bookLocation">
                    <option value="">Select Book Location</option>
                    <option value="HOME">Home</option>
                    <option value="OFFICE">Office</option>
                    <option value="INTO THE MATRIX">Into the Matrix</option>
                </select>
            </div>
            <input type="submit" name="submit" value="Submit">
        </form>
    </div>
</div>

<script type="text/javascript" src="{% static 'books/modifyBooks.js' %}"></script>
{% endblock %}

templates/books/register_books.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Register a book!</h1>

<div class='container' style="justify-content: center; align-items: center;">
    <div class="position-relative">
        <form id="registerBookForm">
            <div class="mb-3">
                <label for="InputTitle" class="form-label">Title: </label>
                <input class="form-control" id="title" type="text" name="title">
            </div>
            <div class="mb-3">
                <label for="InputDescription" class="form-label">Description: </label>
                <input class="form-control" id="description" type="text" name="description">
            </div>
            <div class="mb-3">
                <label for="InputAuthor" class="form-label">Author: </label>
                <input class="form-control" id="authorName" type="text" name="authorName">
            </div>
            <div class="mb-3">
                <label for="InputEmail" class="form-label">Email: </label>
                <input class="form-control" id="authorEmail" type="text" name="authorEmail">
            </div>
            <div class="mb-3">
                <label for="InputCoverImage" class="form-label">Cover Image: </label>
                <input class="form-control" id="coverImage" type="file" name="coverImage">
            </div>
            <div class="mb-3">
                <select class="form-select" aria-label="Default Select Example" id="bookType" name="bookType">
                    <option selected>Select Book Type</option>
                    <option value="PHYSICAL">Physical</option>
                    <option value="PAPERBACK">Paperback</option>
                    <option value="DIGITAL">Digital</option>
                </select>
            </div>
            <div class="mb-3">
                <select class="form-select" aria-label="Default Select Example" id="bookLocation" name="bookLocation">
                    <option selected>Select Book Location</option>
                    <option value="HOME">Home</option>
                    <option value="OFFICE">Office</option>
                    <option value="INTO THE MATRIX">Into the Matrix</option>
                </select>
            </div>
            <input type="submit" name="submit" value="Submit">
        </form>
    </div>
</div>
<script type="text/javascript" src="{% static 'books/registerBooks.js' %}"></script>
{% endblock %}

templates/users/change_password.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-md">
  <form id="changePasswordForm">
      <!-- Old Password input -->
      <div class="form-outline mb-4">
        <label class="form-label" for="oldPassword">Enter Old Password:</label>
        <input type="password" id="oldPassword" class="form-control" />
      </div>
    
      <!-- New Password input -->
      <div class="form-outline mb-4">
        <label class="form-label" for="newPassword1">Enter New Password:</label>
        <input type="password" id="newPassword1" class="form-control" />
      </div>
    
       <!-- New Password Confirm Input -->
      <div class="form-outline mb-4">
        <label class="form-label" for="newPassword2">Confirm New Password:</label>
        <input type="password" id="newPassword2" class="form-control" />
      </div>

      <!-- Submit button -->
      {% comment %} <button type="button" class="btn btn-primary btn-block mb-4">Sign in</button> {% endcomment %}
      <input type="submit" name="changePassword" value="Change Password">

  </form>
</div>


<script type="text/javascript" src="{% static 'users/change_Password.js' %}"></script>
{% endblock %}

templates/users/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>All Users</h1>
<div class="container mt-5 d-flex justify-content-center" id="UserListDisplay"> 
    {% comment %} use tables {% endcomment %}

</div>

<script type="text/javascript" src="{% static 'users/listUsers.js' %}"></script>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-md">
  <form id="loginForm" novalidate>
      <!-- Email input -->
      <div class="form-outline mb-4">
        <input type="email" id="email" class="form-control" />
        <label class="form-label" for="email">Email address</label>
      </div>
    
      <!-- Password input -->
      <div class="form-outline mb-4">
        <input type="password" id="password" class="form-control" />
        <label class="form-label" for="password">Password</label>
      </div>
    
      <!-- 2 column grid layout for inline styling -->
      <div class="row mb-4">
        <div class="col d-flex justify-content-center">
    

      </div>
    
      <!-- Submit button -->
      {% comment %} <button type="button" class="btn btn-primary btn-block mb-4">Sign in</button> {% endcomment %}
      <input type="submit" name="login" value="Submit">
    
      <!-- Register buttons -->

  </form>
</div>


<script type="text/javascript" src="{% static 'users/login.js' %}"></script>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 's Profile{% endblock title %}
{% block content %}

<section class="h-100 gradient-custom-2" id="profileDisplay">

</section>
<script type="text/javascript" src="{% static 'users/profile.js' %}"></script>
{% endblock %}

templates/users/register_user.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Sign up</h1>

<div class='container' style="justify-content: center; align-items: center;">
    <div class="position-relative">
        <form id="registerUserForm" novalidate>
            <div class="mb-3">
                <label for="InputEmail" class="form-label">Email: </label>
                <input class="form-control" id="email" type="text" name="email">
            </div>
            <div class="mb-3">
                <label for="InputPassword" class="form-label">Password: </label>
                <input class="form-control" id="password" type="password" name="password">
            </div>
            <div class="mb-3">
                <label for="InputConfirmPassword" class="form-label">Confirm Password: </label>
                <input class="form-control" id="password2" type="password" name="password2">
            </div>
            <div class="mb-3">
                <label for="InputFirstName" class="form-label">First Name: </label>
                <input class="form-control" id="first_name" type="text" name="first_name">
            </div>
            <div class="mb-3">
                <label for="InputLastName" class="form-label">Last Name: </label>
                <input class="form-control" id="last_name" type="text" name="last_name">
            </div>
            <div class="mb-3">
                <label for="InputAvatar" class="form-label">Profile Picture: </label>
                <input class="form-control" id="avatar" type="file" name="avatar">
            </div>
            <div class="mb-3">
                <label for="InputBio" class="form-label">About Yourself: </label>
                <input class="form-control" id="bio" type="text" name="bio">
            </div>
            <input type="submit" name="submit" value="Submit">
        </form>
    </div>
</div>

<script type="text/javascript" src="{% static 'users/registerUser.js' %}"></script>
{% endblock %}

templates/users/update_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Update Profile</h1>

<div class='container' style="justify-content: center; align-items: center;">
    <div class="position-relative">
        <form id="profileUpdateForm">
            <div class="mb-3">
                <label for="InputFirstName" class="form-label">First Name: </label>
                <input class="form-control" id="first_name" type="text" name="first_name">
            </div>
            <div class="mb-3">
                <label for="InputLastName" class="form-label">Last Name: </label>
                <input class="form-control" id="last_name" type="text" name="last_name">
            </div>
            <div class="mb-3">
                <label for="InputAvatar" class="form-label">Profile Picture: </label>
                <input class="form-control" id="avatar" type="file" name="avatar">
            </div>
            <div class="mb-3">
                <label for="InputBio" class="form-label">About Yourself: </label>
                <input class="form-control" id="bio" type="text" name="bio">
            </div>
            <input type="submit" name="submit" value="Submit">
        </form>
    </div>
</div>

<script type="text/javascript" src="{% static 'users/update_profile.js' %}"></script>
{% endblock %}